// Generated by https://quicktype.io

export interface ProductsService {
    [x: string]: any;
    id:          number;
    title:       string;
    price:       number;
    description: string;
    images:      string[];
    creationAt:  string;
    updatedAt:   string;
    category:    Category;
}

export interface Category {
    id:         number;
    name:       Name;
    image:      string;
    creationAt: string;
    updatedAt:  string;
}

export enum Name {
    Clothes = "Clothes",
    Electronics = "Electronics",
    Furniture = "Furniture",
    Miscellaneous = "Miscellaneous",
    Shoes = "Shoes",
}
